name: Build, push and Deploy

on:
  # Allow to trigger manually and select branch
  workflow_dispatch:

  # Trigger on push to develop branch
#  push:
#    branches:
#      - "develop"
#      - "main"

permissions:
  packages: write

jobs:
  # Build and push stage
  build-push-stage:
    name: 'Build image & push to registry'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ github.repository }}:latest
