name: Container builder

on:
  # Allow to trigger manually
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Custom image TAG"
        required: true
        default: 'latest'
        type: string

  # Trigger on tag push
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  packages: write

jobs:
  # Build and push stage
  build-push-stage:
    name: 'Build image & push to registry'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push Docker image'
        if: ${{ github.ref_type != 'tag' }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/igor-knezevic-vegait/docker-nodejs-sample/test-app:${{ github.event.inputs.image_tag }}

      - name: 'Build and push Docker image'
        if: ${{ github.ref_type == 'tag' }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/igor-knezevic-vegait/docker-nodejs-sample/test-app:${{ github.ref_name }}